apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkpoints
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkpoints
  template:
    metadata:
      labels:
        app: checkpoints
    spec:
      containers:
        - name: checkpoints
          image: armadillo/checkpoints:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"