apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidents
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incidents
  template:
    metadata:
      labels:
        app: incidents
    spec:
      containers:
        - name: incidents
          image: armadillo/incidents:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"